accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path, reverse_lazy
from django.utils.translation import gettext_lazy as _

from . import views

app_name = "accounts"
urlpatterns = [
    path(
        "login/",
        views.LoginView.as_view(
            template_name="login.html",
            redirect_authenticated_user=True,
            extra_context={"title": _("Sign In")},
        ),
        name="login",
    ),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path(
        "password/reset/",
        auth_views.PasswordResetView.as_view(
            template_name="password_reset.html",
            email_template_name="email/password_reset.txt",
            html_email_template_name="email/password_reset.html",
            subject_template_name="email/password_reset_subject.txt",
            success_url=reverse_lazy("accounts:password_reset_done"),
        ),
        name="password_reset",
    ),
    path(
        "password/reset/done/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="password_reset_done.html",
        ),
        name="password_reset_done",
    ),
    path(
        "password/reset/<str:uidb64>/<str:token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="password_reset_confirm.html",
            success_url=reverse_lazy("accounts:password_reset_complete"),
        ),
        name="password_reset_confirm",
    ),
    path(
        "password/reset/complete/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="password_reset_complete.html",
        ),
        name="password_reset_complete",
    ),
    path("register/", views.register, name="register"),
    path("edit_profile/", views.edit_profile, name="edit_profile"),
    path("follow/<str:username>/", views.follow, name="follow"),
    path("unfollow/<str:username>/", views.unfollow, name="unfollow"),
]

blog/urls.py
from django.urls import path

from . import views

app_name = "blog"
urlpatterns = [
    path("", views.index, name="index"),
    path("index/", views.index, name="index"),
    path("explore/", views.explore, name="explore"),
    path("<str:username>/", views.user, name="user"),
]

project/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("", include("blog.urls")),
]

templates/_post.html
{% load i18n %}
{% load avatar %}
{% load dayjs %}

<table class="table table-hover">
  <tr>
    <td width="70px">
      <a href="{% url 'blog:user' username=post.author.username %}">
        <img src="{{ post.author|avatar:70 }}" />
      </a>
    </td>
    <td>
      <a href="{% url 'blog:user' username=post.author.username %}">
        {{ post.author.username }}
      </a>
      {% trans "said" %} {% dayjs_from_now post.timestamp %}:
      <br>
      {{ post.body }}
    </td>
  </tr>
</table>

templates/base.html
{% load i18n %}
{% load static %}
{% load django_bootstrap5 %}
{% load dayjs %}

<!DOCTYPE html>
<html>
<head lang="en">
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  {% bootstrap_css %}
  {% if title %}
    <title>{{ title }} - Microblog</title>
  {% else %}
    <title>{% trans "Welcome to Microblog!" %}</title>
  {% endif %}
</head>
<body>
  <nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container">
      <a class="navbar-brand" href="{% url 'blog:index' %}">Microblog</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{% trans 'Toggle navigation' %}">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="{% url 'blog:index' %}">{% trans "Home" %}</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="{% url 'blog:explore' %}">{% trans "Explore" %}</a>
          </li>
        </ul>
        <ul class="navbar-nav mb-2 mb-lg-0">
          {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" aria-current="page" href="{% url 'blog:user' username=user.username %}">{% trans "Profile" %}</a>
            </li>
            <li class="nav-item">
              <form id="logout-form" action="{% url 'accounts:logout' %}" method="post" style="display: none;">
                {% csrf_token %}
              </form>
              <a class="nav-link" href="#" onclick="document.querySelector('#logout-form').submit(); return false;">{% trans "Logout" %}</a>
            </li>
          {% else %}
            <li class="nav-item">
              <a class="nav-link" aria-current="page" href="{% url 'accounts:register' %}">{% trans "Register" %}</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" aria-current="page" href="{% url 'accounts:login' %}">{% trans "Login" %}</a>
            </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>
  <div class="container mt-3">
    {% bootstrap_messages %}
    {% block content %}{% endblock %}
    {% bootstrap_javascript %}
    {% include_dayjs %}
  </div>
</body>
</html>

templates/edit_profile.html
{% extends "base.html" %}

{% load i18n %}
{% load django_bootstrap5 %}

{% block content %}
  <h1>{% trans "Edit Profile" %}</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {% bootstrap_form form %}
    {% bootstrap_button button_type="submit" content=_("Submit") %}
  </form>
{% endblock %}

templates/index.html
{% extends "base.html" %}

{% load i18n %}
{% load django_bootstrap5 %}

{% block content %}
  <h1>{% blocktrans with username=user.username %}Hi, {{ username }}!{% endblocktrans %}</h1>
  {% if form %}
    <form action="" method="post">
      {% csrf_token %}
       {% bootstrap_field form.body show_label=False %}
      {% bootstrap_button button_type="submit" content=_("Submit") %}
    </form>
  {% endif %}
  {% for post in posts %}
    {% include '_post.html' %}
  {% endfor %}
  <nav aria-label="{% trans 'Post navigation' %}">
    <ul class="pagination">
      <li class="page-item{% if not prev_url %} disabled{% endif %}">
        <a class="page-link" href="{{ prev_url }}">
          <span aria-hidden="true">&larr;</span> {% trans "Newer posts" %}
        </a>
      </li>
      <li class="page-item{% if not next_url %} disabled{% endif %}">
        <a class="page-link" href="{{ next_url }}">
          {% trans "Older posts" %} <span aria-hidden="true">&rarr;</span>
        </a>
      </li>
    </ul>
  </nav>
{% endblock %}

templates/login.html
{% extends "base.html" %}

{% load i18n %}
{% load django_bootstrap5 %}

{% block content %}
  <h1>{% trans "Sign In" %}</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {% bootstrap_form form %}
    {% bootstrap_button button_type="submit" content=_("Sign In") %}
  </form>
  <p>
    {% trans "New User?" %}
    <a href="{% url 'accounts:register' %}">{% trans "Click to Register!" %}</a>
  </p>
  <p>
    {% trans "Forgot Your Password?" %}
    <a href="{% url 'accounts:password_reset' %}">{% trans "Click to Reset It" %}</a>
  </p>
{% endblock %}

templates/password_reset.html
{% extends "base.html" %}

{% load i18n %}
{% load django_bootstrap5 %}

{% block content %}
  <h1>{% trans "Reset Password" %}</h1>
  <form action="" method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% bootstrap_button button_type="submit" content=_("Request Password Reset") %}
  </form>
{% endblock %}

templates/password_reset_complete.html
{% extends "base.html" %}

{% load i18n %}

{% block content %}
  <h1>{% trans "Reset Password" %}</h1>
  <p>
    {% trans "You have successfully changed your password! You may now proceed to log in." %}
  </p>
  <p><a href="{% url 'accounts:login' %}">{% trans "Return to Sign In" %}</a></p>
{% endblock %}

templates/password_reset_confirm.html
{% extends "base.html" %}

{% load i18n %}
{% load django_bootstrap5 %}

{% block content %}
  <h1>{% trans "Reset Password" %}</h1>
  {% if validlink %}
    <form action="" method="post">
      {% csrf_token %}
      {% bootstrap_form form %}
      {% bootstrap_button button_type="submit" content=_("Change Password") %}
    </form>
  {% else %}
    <p>{% trans "It looks like you clicked on an invalid password reset link. Please try again." %}</p>
  {% endif %}
{% endblock %}

templates/password_reset_done.html
{% extends "base.html" %}

{% load i18n %}

{% block content %}
  <h1>{% trans "Reset Password" %}</h1>
  <p>
    {% trans "Check your email for a link to reset your password. If it doesn't appear within a few minutes, check your spam folder." %}
  </p>
  <p><a href="{% url 'accounts:login' %}">{% trans "Return to Sign In" %}</a></p>
{% endblock %}

templates/register.html
{% extends "base.html" %}

{% load i18n %}
{% load django_bootstrap5 %}

{% block content %}
  <h1>{% trans "Register" %}</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {% bootstrap_form form %}
    {% bootstrap_button button_type="submit" content=_("Register") %}
  </form>
{% endblock %}

templates/user.html
{% extends "base.html" %}

{% load i18n %}
{% load django_bootstrap5 %}
{% load avatar %}
{% load dayjs %}

{% block content %}
  <table class="table table-hover">
    <tr>
      <td width="256px"><img src="{{ user_|avatar:256 }}"></td>
      <td>
        <h1>{% blocktrans with username=user_.username %}User: {{ username }}{% endblocktrans %}</h1>
        {% if user_.about_me %}<p>{{ user_.about_me }}</p>{% endif %}
        {% if user_.last_seen %}<p>{% trans "Last seen on:" %} {% dayjs_format user.last_seen 'LLL' %}</p>{% endif %}
        {% if user_ == user %}
          <p><a href="{% url 'accounts:edit_profile' %}">{% trans "Edit your profile" %}</a></p>
        {% elif not following %}
          <form action="{% url 'accounts:follow' username=user_.username %}" method="post" novalidate>
            {% csrf_token %}
            {% bootstrap_button button_type="submit" content=_("Follow") %}
          </form>
        {% else %}
          <form action="{% url 'accounts:unfollow' username=user_.username %}" method="post" novalidate>
            {% csrf_token %}
            {% bootstrap_button button_type="submit" content=_("Unfollow") %}
          </form>
        {% endif %}
      </td>
    </tr>
  </table>
  {% for post in posts %}
    {% include '_post.html' %}
  {% endfor %}
  <nav aria-label="{% trans 'Post navigation' %}">
    <ul class="pagination">
      <li class="page-item{% if not prev_url %} disabled{% endif %}">
        <a class="page-link" href="{{ prev_url }}">
          <span aria-hidden="true">&larr;</span> {% trans "Newer posts" %}
        </a>
      </li>
      <li class="page-item{% if not next_url %} disabled{% endif %}">
        <a class="page-link" href="{{ next_url }}">
          {% trans "Older posts" %} <span aria-hidden="true">&rarr;</span>
        </a>
      </li>
    </ul>
  </nav>
{% endblock %}